### ISSUE TITLE
 Implement Error Handling for API Calls in Frontend

### ISSUE THREAD

**Issue by OhmSpectator** [OhmSpectator/track-your-regions#86]
## Description
Currently, our frontend components make several API calls without a consistent error handling strategy. This can lead to unhandled exceptions and a poor user experience when network requests fail or return unexpected results. We need to develop and implement a robust error handling mechanism across all components that interact with the API.

## Scope
- Review all existing API calls in the frontend codebase.
- Design a standardized error handling approach that can be applied universally to all API interactions.
- Ensure that the user is appropriately notified of any issues, and the application can gracefully handle API failures.

## Acceptance Criteria
- All API calls in the frontend are wrapped with try-catch blocks or use promise chaining with `.catch()` to handle errors.
- Error handling includes logging for developers and user-friendly notifications where appropriate.
- Components have fallback states or behaviors defined for when API calls fail.

## Out of Scope
- Backend error handling and logging.

## Notes
- Consider using a global error handling context or a higher-order component to manage repetitive error handling logic.
- This issue does not require immediate resolution but should be addressed progressively to improve the stability and reliability of the application.

**Comment by OhmSpectator** [comment]
Sometimes I return empty values ([], null), and sometimes I throw an error. I have to stick to one approach.

**Comment by pbelokon** [comment]
@OhmSpectator  I can give this a shot

**Comment by OhmSpectator** [comment]
@pbelokon sure!

**Comment by pbelokon** [comment]
> @pbelokon sure!

Thanks !
